apply plugin: 'com.android.application'

android {
    compileSdk = 36
    buildToolsVersion = '36.0.0'
    namespace "com.tr.onjestslowo.app"
    defaultConfig {
        applicationId "com.tr.onjestslowo.app"
        minSdkVersion 28
        targetSdkVersion 36
        versionCode 246
        versionName '2.4.6'
    }

    buildFeatures {
        // Set buildConfig to true to enable BuildConfig generation
        buildConfig true
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
    productFlavors {
    }
}


dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    api  fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation "androidx.preference:preference:1.2.1"
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'com.google.firebase:firebase-core:16.0.9'
}

apply plugin: 'com.google.gms.google-services'